export type Locale = "ar" | "en";

export const UI: Record<string, string> = {
  "المطاعم": "Restaurants", "طلباتي": "My orders", "العروض": "Offers", "الشروط والأحكام": "Terms & conditions", "لوحة المتاجر": "Restaurant partners", "مندوبي التوصيل": "Couriers", "السلة": "Cart", "دخول العميل": "Sign in", "دخول / حساب جديد": "Sign in / Join", "دعم واتساب مباشر": "WhatsApp support", "الكل": "All", "كل المناطق": "All areas", "المحافظة": "Governorate", "المنطقة": "Area", "المطابخ": "Cuisines", "موقع التوصيل": "Delivery location", "مطعم": "restaurants", "مفتوح": "Open", "مزدحم": "Busy", "مغلق": "Closed", "جديد": "New", "تقييم": "reviews", "أقل طلب": "Minimum order", "افتح القائمة": "View menu", "تصفح المطاعم": "Explore restaurants", "دفع إلكتروني فقط — بطاقة أو بنفت باي": "Secure online payment · card or BenefitPay", "لا توجد مطاعم مطابقة لهذا الفلتر — جرّب محافظة أو مطبخاً آخر.": "No restaurants match these filters. Try another area or cuisine.", "سجل حسابك": "Create an account", "تسجيل الدخول": "Sign in", "حساب جديد": "Create account", "الاسم الكامل": "Full name", "رقم الهاتف": "Phone number", "البريد الإلكتروني": "Email address", "كلمة المرور": "Password", "عنوان التوصيل": "Delivery address", "تفعيل البريد": "Verify email", "إتمام الطلب": "Checkout", "العنوان بالتفصيل": "Full address", "طريقة الدفع": "Payment method", "بنفت باي": "BenefitPay", "بطاقة ائتمانية / خصم": "Credit / debit card", "ملخص الطلب": "Order summary", "رسوم التوصيل": "Delivery fee", "المجموع": "Subtotal", "الإجمالي": "Total", "كود الخصم": "Promo code", "الدفع الآمن عبر بوابة Tap": "Secure checkout via Tap Payments", "العميل": "Customer", "لوحة الطلبات": "Orders", "الطلبات": "Orders", "القائمة": "Menu", "التقارير": "Reports", "العروض والخصومات": "Promotions", "الحالة": "Status", "الأرباح": "Earnings", "حسابي": "Account", "نظرة عامة": "Overview", "المتاجر": "Stores", "المندوبون": "Couriers", "العملاء": "Customers", "المناطق": "Locations", "الأسعار": "Pricing", "المالية": "Finance", "المديرون": "Admins", "المحتوى": "Content", "خروج": "Sign out", "المحافظات": "Governorates", "إضافة": "Add", "تعديل": "Edit", "حذف": "Delete", "حفظ": "Save", "إلغاء": "Cancel", "تأكيد": "Confirm", "جارٍ التحميل…": "Loading…", "لوحة تحكم الأدمن": "Administration login", "دخول إدارة لقمة": "Luqma administration", "انضم كمتجر": "Partner with us", "انضم كمندوب": "Become a courier", "سياسة الخصوصية": "Privacy policy", "العودة للمطاعم": "Back to restaurants", "قيد المراجعة": "Under review", "تم التوصيل": "Delivered", "في الطريق إليك": "On the way", "قيد التحضير": "Preparing", "من": "From", "إلى": "To", "حفظ ونشر التغييرات": "Save & publish", "اللغة": "Language",
};

export function translate(text: string, locale: Locale) {
  return locale === "en" ? UI[text] ?? text : text;
}
